---
title: "Shiny_Final"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r global, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(tidyverse)
library(sf)
library(tigris)
library(mapview)
library(leaflet)
library(censusapi)
library(gtools)
Sys.setenv(CENSUS_KEY="9fbd5ddd430b595b8f3715733cae2b75c18be92e")



pums_2019_1yru <- readRDS("usa_pums.rds")

us_pumas <-
  pumas(state = NULL, cb = T, progress_bar = F)

counties <-
  counties(state = NULL, cb = T, progress_bar = F)

us_pumas <-
  us_pumas %>% 
  st_centroid() %>% 
  .[counties, ] %>% 
  st_drop_geometry() %>% 
  left_join(us_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

us_pums <-
  pums_2019_1yru %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% us_pumas$PUMACE10)




## cleaned us
cleaned <- us_pums %>%
  mutate(
    SPORDER = as.numeric(SPORDER),
    CPLT = as.numeric(CPLT)
  ) %>% 
  filter(
    (SPORDER %in% 1:2), #Only using head of household data so that household income is not double counted thus skewing results.
    (CPLT %in% 1:4)) #filtering out N/A




## us pop data
us_pums_pop <-
  cleaned %>%
  filter(
    (RAC1P %in% c(1,2,3,6,9))) %>% 
  mutate(
    same_sex = ifelse(
        (CPLT == 2)|(CPLT == 4),
        1,
        0
  )) %>% 
  group_by(PUMA) %>% 
  summarize(
    samesex = sum(same_sex, na.rm = T),
    total_pop = sum(CPLT, na.rm = T)
  ) %>% 
  mutate(
    percent = samesex/total_pop*100
  ) %>% 
    left_join(
    us_pumas %>% 
      select(PUMACE10),
    by = c("PUMA" = "PUMACE10")
  ) %>% 
  st_as_sf()
```


Inputs {.sidebar}
-------------------------------------

```{r}
checkboxGroupInput(
  inputId = "year",
  label = "Year: ",
  choices = 2017:2020,
  selected = 2020
)
```

```{r}
selectInput(
  inputId = "class",
  label = "Energy Type: ",
  choices = c("Residential Electricity" = "Elec- Residential",
              "Commercial Electricity" = "Elec- Commercial", 
              "Residential Gas" = "Gas- Residential",
              "Commercial Gas" = "Gas- Commercial"),
  selected = "Residential Electricity"
)
```


Column
-------------------------------------

### USA Map

```{r}
leafletOutput("map")
```

```{r, context = "server"}
observeEvent({
  input$year
  input$class},
  { 
couple_pal <- colorNumeric(
  palette = "Blues",
  domain = 
    c(0,5)
)

output$map <- renderLeaflet({
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = us_pums_pop, 
    fillColor = ~couple_pal (percent),
    color = "white",
    opacity = 0.5,
    fillOpacity = 0.75,
    weight = 1,
    label = ~paste0(
      round(percent*100)/100,
      "% same-sex couples"
    ),
    highlightOptions = highlightOptions(
      weight = 2,
      opacity = 1
    )
  ) %>% 
  addLegend(
    data = us_pums_pop,
    pal = couple_pal,
    values = 0:5,
    title = "% same-sex relationships"
  )
})

})

```


Column
-------------------------------------

<!-- ### ZCTA consumption -->

<!-- ```{r} -->
<!-- plotlyOutput("plot") -->
<!-- ``` -->

<!-- ```{r, context = "server"} -->
<!-- observeEvent({ -->
<!--   input$year -->
<!--   input$class}, { # wrapper to make it listen to changes in input$year and update the display accordingly -->
<!--   # Identify correct label for energy type -->
<!--   class <- input$class -->
<!--   if (class == "Elec- Residential") class = "Residential Electricity" -->
<!--   else if (class == "Elec- Commercial") class = "Commercial Electricity" -->
<!--   else if (class == "Gas- Residential") class = "Residential Gas" -->
<!--   else if (class == "Gas- Commercial") class = "Commercial Gas" -->

<!--   chart <- us_pums_IRC %>%  -->
<!--   group_by(income, race) %>%  -->
<!--   summarize(estimate = sum(PWGTP)) %>%  -->
<!--   rbind(us_race_total) %>%   -->
<!--   ggplot() + -->
<!--   geom_bar( -->
<!--     aes( -->
<!--       x = income %>% factor(levels = rev(c("Total", mixedsort(order)))), -->
<!--       y = estimate, -->
<!--       fill = race  -->
<!--     ), -->
<!--     stat = "identity", -->
<!--     position = "fill" -->
<!--   ) + -->
<!--   labs( -->
<!--     x = "Household income", -->
<!--     y = "Number of households", -->
<!--     title = "US personal income by race: Individuals in same-sex relationships", -->
<!--     fill = "Race" -->
<!--   ) + -->
<!--   coord_flip() + -->
<!--   theme( -->
<!--     legend.position = "bottom", -->
<!--     legend.direction = "vertical" -->
<!--   )  + -->
<!--   guides( -->
<!--     fill = guide_legend( -->
<!--       reverse = T -->
<!--     ) -->
<!--   ) -->

<!--   output$plot <- renderPlotly({ # wrapper to keep output dynamic  -->
<!--     chart %>%  -->
<!--       ggplotly() %>%  -->
<!--       config(displayModeBar = F) -->
<!--   }) -->

<!-- }, -->
<!--   ignoreNULL = T) -->

<!-- ``` -->