---
title: "Dashboard Final Project - Kaden & David"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r global, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(plotly)
library(tidyverse)
library(sf)
library(tigris)
library(mapview)
library(leaflet)
library(censusapi)
library(gtools)
library(shiny)


order <- c( "$20,000 or less", "$20,001 to $50,000","$50,001 to $80,000","$80,001 to $100,000","$100,001 to $150,000","$150,001 to $200,000","$200,001 to $250,000","$250,001 or more")


usa_pums_pop <- readRDS("usa_pums_pop.rds")
usa_chart_data <- readRDS("usa_chart_data.rds")


```


Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(
  inputId = "location",
  label = "Location: ",
  choices = c("USA",
              "Florida", 
              "California"),
  selected = "USA"
)
```

```{r}
selectInput(
  inputId = "couple_type",
  label = "Couple Type: ",
  choices = c("Same-sex couples",
              "Opposite-sex couples"),
  selected = "Same-sex couples"
)
```


Column
-------------------------------------

### Equity Analysis of Same-sex/Opposite-sex couples by Race

```{r}
plotlyOutput("plot")
```

```{r, context = "server"}
observeEvent({
  input$location
  input$couple_type}, {
    
  chart <- usa_chart_data %>%  
  ggplot() +
  geom_bar(
    aes(
      x = income %>% factor(levels = rev(c("Total", mixedsort(order)))),
      y = estimate,
      fill = race 
    ),
    stat = "identity",
    position = "fill"
  ) +
  labs(
    x = "Household income",
    y = "Number of households",
    title = "US personal income by race: Individuals in same-sex relationships",
    fill = "Race"
  ) +
  coord_flip() +
  theme(
    legend.position = "bottom",
    legend.direction = "vertical"
  )  +
  guides(
    fill = guide_legend(
      reverse = T
    )
  )

  output$plot <- renderPlotly({
    chart %>%
      ggplotly() %>%
      config(displayModeBar = F)
  })

},
  ignoreNULL = T)

```



<!-- Column -->
<!-- ------------------------------------- -->

<!-- ```{r} -->



<!-- ``` -->




<!-- ### USA Map -->

<!-- ```{r} -->
<!-- leafletOutput("map") -->
<!-- ``` -->

<!-- ```{r, context = "server"} -->
<!-- observeEvent({ -->
<!--   input$year -->
<!--   input$class}, -->
<!--   {  -->
<!-- couple_pal <- colorNumeric( -->
<!--   palette = "Blues", -->
<!--   domain =  -->
<!--     c(0,5) -->
<!-- ) -->

<!-- output$map <- renderLeaflet({ -->
<!-- leaflet() %>%  -->
<!--   addProviderTiles(providers$CartoDB.Positron) %>%  -->
<!--   addPolygons( -->
<!--     data = usa_pums_pop,  -->
<!--     fillColor = ~couple_pal (percent), -->
<!--     color = "white", -->
<!--     opacity = 0.5, -->
<!--     fillOpacity = 0.75, -->
<!--     weight = 1, -->
<!--     label = ~paste0( -->
<!--       round(percent*100)/100, -->
<!--       "% same-sex couples" -->
<!--     ), -->
<!--     highlightOptions = highlightOptions( -->
<!--       weight = 2, -->
<!--       opacity = 1 -->
<!--     ) -->
<!--   ) %>%  -->
<!--   addLegend( -->
<!--     data = usa_pums_pop, -->
<!--     pal = couple_pal, -->
<!--     values = 0:5, -->
<!--     title = "% same-sex relationships" -->
<!--   ) -->
<!-- }) -->

<!-- }) -->

<!-- ``` -->



